Add Feedback Fish
workos-inc/awesome-developer-experience pull request #17
Opened 2021-07-23 02:28 UTC by adoniasvitorio

Hi @zenorocha !

My new suggest is **Feedback Fish** as product.

Thanks !

2021-07-23 22:40 UTC, zenorocha commented on README.md
> +| [Feedback Fish](https://feedback.fish/)                  | A simple way to collect feedback & make your customers happy..                                          | 2020         |
Double `..`

2021-07-23 22:40 UTC, zenorocha requested changes
Looking good! Once you fix the typo, I can merge the PR ;)

2021-07-23 23:03 UTC, adoniasvitorio commented
fix `..`

2021-07-27 17:19 UTC, bukinoshita commented
Looks good to me! Let's merge 🎉

2021-07-27 17:19 UTC, merged